# Generated by ./update.sh - do not update manually!
# Last updated: 2023-11-14
{
  version = "3.2.3-19689";
  urlhash = "5edc39d1";
  amd64_hash = "sha256-3WkdE5U+m59ZAA7EVQwePtujD2szsZsgsNzpjcp/oCI=";
}
