# Generated by ./update.sh - do not update manually!
# Last updated: 2023-11-14
{
  version = "3.2.3-19480";
  urlhash = "683f4917";
  amd64_hash = "sha256-DItJ6N/ouaUrYYZgubGiz9djSILtTjCP9vh4FDANr2A=";
}
